#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Script: deprecated.py
Author: 
Date: 
Description: 
    deprecated classes / functions
"""

# ----------------------------------------------------------------------------------------------------------------------------
# Imports
import keras
from povm_sampling import *
from utils import *

# ----------------------------------------------------------------------------------------------------------------------------
# Costants


# ----------------------------------------------------------------------------------------------------------------------------
# Functions and classes

class FidelityMonitor(keras.callbacks.Callback):
    """
    Keras callback to monitor the classical fidelity at the end of each epoch
        Input args:
            P_exact: the exact probability distribution over the POVM outcomes
            n_qubits: the number of qubits in the system
            n_gen: the number of samples to generate from the model for estimating the fidelity (n_e)
            seed: the random seed for reproducibility
    """
    def __init__(self, P_exact, n_qubits, n_gen=20000, seed=0):
        super().__init__()
        self.P_exact = P_exact
        self.n_qubits = n_qubits
        self.n_gen = n_gen
        self.seed = seed

    def vae_generate(self, model, n_samples):
        '''Generates samples from vae decoder. It samples the softmax dist of each qubit'''
        rng = np.random.default_rng(self.seed)
        # sample the probability of each possible outcome
        probs = model.sample(n_samples).numpy().reshape(n_samples, self.n_qubits, 4)  # (n, N, 4)

        # extract a single class for each group by probs distributions
        # (argmax does not consider the softmax dist for onehot digits)
        cum = np.cumsum(probs, axis=-1)                 # (n, N, 4)
        u = rng.random((n_samples, self.n_qubits, 1))   # (n, N, 1)
        # draws is boolean (n, N, 4) --> argmax(-1) return position of the 1st True 
        draws = (u < cum).argmax(axis=-1)               # (n, N) povm outcome
        return [tuple(int(a) for a in row) for row in draws]
    
    # def classical_fidelity(self, P, Q):
    #     return float(sum(np.sqrt(P.get(x, 0.0) * Q.get(x, 0.0)) for x in set(P) | set(Q)))
    
    def total_variation(self, P, Q):
        '''TV = 1/2 sum|P-Q|: 0=same'''
        return float(0.5 * sum(abs(P.get(x, 0.0) - Q.get(x, 0.0)) for x in set(P) | set(Q)))
    
    def on_epoch_end(self, epoch, logs=None):
        '''Compute and log classical fidelity. Automatically called at the end of each epoch by Keras'''
        # create samples
        gen = self.vae_generate(self.model, self.n_gen)
        # compute empirical dist
        P_vae = samples_to_empirical_dist(gen, self.n_qubits)
        # compute classical fidelity
        Fc = classical_fidelity(self.P_exact, P_vae)
        # ensures logs exist, then log val_fidelity 
        logs = logs if logs is not None else {}
        logs['val_fidelity'] = Fc


def plot_distribution_compare(self, p_true, p_gen, p_train, outcomes=None):
        """
        Plot a comparison of three distributions: the true distribution (p_true), the distribution generated by the VAE (p_gen), and the distribution from the training data (p_train).
        Args:
            p_true: list or array of true probabilities for each outcome (e.g., from GHZ state)
            p_gen: list or array of probabilities generated by the VAE
            p_train: list or array of probabilities from the training data (shot noise)
            outcomes: optional list of outcome labels (e.g., tuples of POVM outcomes) to use as x-axis ticks
        """
        p_true  = np.asarray(p_true,  dtype=float)
        p_gen   = np.asarray(p_gen,   dtype=float)
        p_train = np.asarray(p_train, dtype=float)
        n = len(p_true)
        x = np.arange(n)

        w_out = 0.95   # larghezza barra-contenitore (P esatta)
        w_in  = 0.25   # larghezza barre interne (train / VAE), due affiancate dentro w_out

        _, ax = plt.subplots(figsize=(10, 5))

        # contenitore: P esatta come barra larga, contorno netto + riempimento molto tenue
        ax.bar(x, p_true, width=w_out,
               facecolor='white', edgecolor='black', linewidth=0.8,
               label='P esatta (GHZ)', zorder=1)

        # due barre sottili affiancate dentro ogni contenitore
        ax.bar(x - w_in / 2, p_train, width=w_in, color='C0', zorder=2,
               label='P training (shot noise)')
        ax.bar(x + w_in / 2, p_gen,   width=w_in, color='C1', zorder=2,
               label='P VAE')

        ax.axhline(1 / n, ls='--', c='gray', lw=1.0, zorder=0, label='uniforme (floor)')

        # etichette = tuple degli outcome (es. "013"), ruotate per leggibilita'
        if outcomes is not None:
            ticks = [''.join(map(str, o)) if hasattr(o, '__iter__') else str(o) for o in outcomes]
            ax.set_xticks(x)
            ax.set_xticklabels(ticks, rotation=90, fontsize=6.5, family='monospace')
            ax.set_xlabel('outcome POVM  (a$_1$a$_2$a$_3$)', fontsize=11)
        else:
            ax.set_xlabel('indice outcome', fontsize=11)

        ax.set_xlim(-0.7, n - 0.3)
        ax.set_ylabel('probabilità', fontsize=11)
        ax.set_title('POVM 3 qubit: esatta (contenitore) vs training / VAE (barre interne)',
                     fontsize=12, pad=10)
        ax.tick_params(axis='y', labelsize=10)
        ax.grid(axis='y', ls=':', alpha=0.4)
        ax.legend(fontsize=10, framealpha=0.85, loc='upper right')

        plt.tight_layout()
        plt.show()

# ----------------------------------------------------------------------------------------------------------------------------
if __name__ == "__main__": 
    print('deprecate.py has no main.')
