import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

def plot_reconstruction_and_kl_divergence(history):
    """
    Plot the reconstruction loss and KL divergence over epochs from the training history.
    It extracts the relevant losses from the history object and plots them on the same graph for comparison.
    Args:
        history: Keras History object returned by model.fit(), containing the loss values for each epoch
    """
    reconstruction_losses = {key: history.history[key] for key in history.history.keys() if 'reconstruction' in key}
    kl_losses = {key: history.history[key] for key in history.history.keys() if 'kl' in key and 'weight' not in key}

    plt.figure(figsize=(8, 6))
    for key, values in reconstruction_losses.items():
        plt.plot(values, label=key)
    for key, values in kl_losses.items():
        plt.plot(values, label=key)
    plt.title('Reconstruction Loss and KL Divergence')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def plot_total_loss(history):
    """
    Plot the total loss over epochs from the training history. It extracts the total loss values from the history object and plots them.
    Args:
        history: Keras History object returned by model.fit(), containing the loss values for each epoch
    """
    total_losses = {key: history.history[key] for key in history.history.keys() if 'loss' in key and 'reconstruction' not in key and 'kl' not in key}

    plt.figure(figsize=(8, 6))
    for key, values in total_losses.items():
        plt.plot(values, label=key)
    plt.title('Total Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def plot_distribution_delta(p_true, p_gen, p_train, outcomes=None,
                            sort_by='true', annotate_metrics=True):
    """
    Compare the true distribution (p_true), the VAE-generated distribution (p_gen), and the training distribution (p_train) 
    by plotting their differences (delta) from the true distribution.
    Args:
        p_true: list or array of true probabilities for each outcome (e.g., from GHZ state)
        p_gen: list or array of probabilities generated by the VAE
        p_train: list or array of probabilities from the training data (shot noise)
        outcomes: optional list of outcome labels (e.g., tuples of POVM outcomes) to use as x-axis ticks
        sort_by: 'true' to sort by true probabilities, 'none' to keep original order (default: 'true')
        annotate_metrics: whether to calculate and display TVD metrics in the legend (default: True)
    """
    p_true  = np.asarray(p_true,  dtype=float)
    p_gen   = np.asarray(p_gen,   dtype=float)
    p_train = np.asarray(p_train, dtype=float)
    n = len(p_true)

    # ordinamento per leggibilita': outcome dominanti (P_true alta) a sinistra
    order = np.argsort(p_true)[::-1] if sort_by == 'true' else np.arange(n)
    p_true, p_gen, p_train = p_true[order], p_gen[order], p_train[order]

    # scostamenti dalla distribuzione esatta (= 0)
    d_train = p_train - p_true
    d_gen   = p_gen   - p_true
    x = np.arange(n)

    _, ax = plt.subplots(figsize=(11, 5))

    # linea di riferimento: distribuzione esatta -> Delta = 0
    ax.axhline(0.0, color='black', lw=1.2, zorder=3, label='P esatta (riferimento, Δ=0)')

    # stem (segmentini verticali) per guidare l'occhio dallo zero al punto
    ax.vlines(x, 0, d_train, color='C0', alpha=0.25, lw=0.8, zorder=1)
    ax.vlines(x, 0, d_gen,   color='C1', alpha=0.25, lw=0.8, zorder=1)

    # TVD (total variation distance) come metrica sintetica di distanza
    if annotate_metrics:
        tvd_train = 0.5 * np.sum(np.abs(d_train))
        tvd_gen   = 0.5 * np.sum(np.abs(d_gen))
        lab_train = f'Δ training (shot noise)   TVD={tvd_train:.3f}'
        lab_gen   = f'Δ VAE   TVD={tvd_gen:.3f}'
    else:
        lab_train, lab_gen = 'Δ training (shot noise)', 'Δ VAE'

    ax.scatter(x, d_train, s=28, color='C0', edgecolor='white', linewidth=0.4,
               zorder=4, label=lab_train)
    ax.scatter(x, d_gen, s=28, color='C1', edgecolor='white', linewidth=0.4,
               marker='D', zorder=4, label=lab_gen)

    # etichette = tuple degli outcome (es. "013"), ruotate per leggibilita'
    if outcomes is not None:
        outcomes = [outcomes[i] for i in order]
        ticks = [''.join(map(str, o)) if hasattr(o, '__iter__') else str(o) for o in outcomes]
        ax.set_xticks(x)
        ax.set_xticklabels(ticks, rotation=90, fontsize=6.5, family='monospace')
        ax.set_xlabel('outcome POVM  (ordinati per P esatta decrescente)', fontsize=11)
    else:
        ax.set_xlabel('indice outcome  (ordinati per P esatta decrescente)', fontsize=11)

    ax.set_xlim(-0.7, n - 0.3)
    ax.set_ylabel('Δ probabilità  (P − P esatta)', fontsize=11)
    ax.set_title('Scostamento da P esatta: training vs VAE', fontsize=12, pad=10)
    ax.tick_params(axis='y', labelsize=10)
    ax.grid(axis='y', ls=':', alpha=0.4)
    ax.legend(fontsize=9, framealpha=0.9, loc='best')

    plt.tight_layout()
    plt.show()

def plot_fidelity_vs_samples(self, results):
    """
    Plot the classical fidelity (Fc) as a function of the number of samples used for training, for different numbers of qubits.
    Args:
        results: dict of the form {n_qubits: {'n_samples': [...], 'Fc': [...]}} containing the number of samples and corresponding fidelities for each qubit count. 
    """
    plt.figure(figsize=(8, 5))
    colors = plt.cm.viridis(np.linspace(0, 0.85, len(results)))

    for color, (q, r) in zip(colors, sorted(results.items())):
        ns = r["n_samples"]
        plt.plot(ns, r["Fc"], '-o', color=color, label=f'{q} qubit (VAE)')

    plt.xscale('log')
    plt.xlabel('N_SAMPLES (campioni di training)')
    plt.ylabel('Fidelity classica  $F_c$')
    plt.title('Fidelity classica vs N_SAMPLES from 3 to 8 qubit')
    plt.grid(True, which='both', ls=':', alpha=0.5)
    plt.legend()
    plt.tight_layout()
    plt.show()