#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Script: plots.py
Author: Riccardo Ruggeri
Description: 
    It provides shortcuts to recurrent usefull plots.
"""

# ----------------------------------------------------------------------------------------------------------------------------
# Imports
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# ----------------------------------------------------------------------------------------------------------------------------
# Functions and classes

def plot_reconstruction_and_kl_divergence(history, title=True):
    """
    Plot the reconstruction loss and KL divergence over epochs from the training history.
    It extracts the relevant losses from the history object or a loaded DataFrame/dict
    and plots them on the same graph for comparison.
    
    Args:
        history: Keras History object OR pandas DataFrame/dict containing the loss values
        title: default=True
    Returns: figure 
    """
    # -- input validation --
    data_source = history.history if hasattr(history, 'history') else history   # dict of History keras class
    keys = data_source.keys() if hasattr(data_source, 'keys') else data_source.columns

    reconstruction_losses = {key: data_source[key] for key in keys if 'reconstruction' in key}
    kl_losses = {key: data_source[key] for key in keys if 'kl' in key and 'weight' not in key}

    fig, ax = plt.subplots(figsize=(8, 6))
    for key, values in reconstruction_losses.items():
        ax.plot(values, label=key)
    for key, values in kl_losses.items():
        ax.plot(values, label=key)
        
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.legend()
    ax.grid(True, which='both', ls=':', alpha=0.5)
    
    if title:
        ax.set_title('Reconstruction Loss and KL Divergence')

    fig.tight_layout()
    plt.show()

    return fig


def plot_total_loss(history, title=True):
    """
    Plot the total loss over epochs from the training history. 
    It extracts the total loss values from the history object or a loaded DataFrame/dict and plots them.
    
    Args:
        history: Keras History object OR pandas DataFrame/dict containing the loss values
        title: default=True
    Returns: figure 
    """
    # -- input validation --
    data_source = history.history if hasattr(history, 'history') else history   # dict of History keras class
    keys = data_source.keys() if hasattr(data_source, 'keys') else data_source.columns

    # Estrae solo le perdite totali (es. 'loss' e 'val_loss'), escludendo i sotto-componenti
    total_losses = {key: data_source[key] for key in keys if 'loss' in key and 'reconstruction' not in key and 'kl' not in key}

    fig, ax = plt.subplots(figsize=(8, 6))
    for key, values in total_losses.items():
        ax.plot(values, label=key)
        
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.legend()
    ax.grid(True, which='both', ls=':', alpha=0.5)
    
    if title:
        ax.set_title('Total Loss')

    fig.tight_layout()
    plt.show()

    return fig


def plot_distribution_delta(p_true, p_gen, p_train, sort_by='true', abs=True,
                             highlight_lines=True, highlight_markers=True,
                             x_ticks_mode='prob_reference', title=True):
    """
    Compare p_true, p_gen, and p_train by plotting their differences from p_true.
    
    Args:
        p_true (array-like): True probabilities for each outcome.
        p_gen (array-like): Probabilities generated by the VAE.
        p_train (array-like): Probabilities from the training data (shot noise).
        sort_by (str): 'true' to sort by decreasing true probabilities, 'none' otherwise.
        abs (bool): If True, plots the absolute value of the deviations.
        highlight_lines (bool): If True, draws a thicker line for the winning method.
        highlight_markers (bool): If True, increases the marker size for the winning method.
        x_ticks_mode (str): 'prob_reference' to show selected p_exact values, 
                            'none' to hide ticks entirely, 'all' for standard index ticks.
        title (bool): If True, prints the title
    Returns: figure 
    """
    p_true  = np.asarray(p_true,  dtype=float)
    p_gen   = np.asarray(p_gen,   dtype=float)
    p_train = np.asarray(p_train, dtype=float)
    n = len(p_true)

    # order of the outcomes
    order = np.argsort(p_true)[::-1] if sort_by == 'true' else np.arange(n)
    p_true, p_gen, p_train = p_true[order], p_gen[order], p_train[order]

    # deltas
    d_train = p_train - p_true
    d_gen   = p_gen   - p_true
    
    # best estimations
    err_train_abs = np.abs(d_train)
    err_gen_abs   = np.abs(d_gen)
    vae_wins = err_gen_abs < err_train_abs
    train_wins = ~vae_wins
    
    if abs:
        d_train = err_train_abs
        d_gen   = err_gen_abs

    x = np.arange(n)
    fig, ax = plt.subplots(figsize=(11, 5))

    # p_exact --> 0 line
    ax.axhline(0.0, color='black', lw=1.2, zorder=3, label='$p_{exact} (\\Delta=0)$')
    
    # vlines
    if highlight_lines:
        ax.vlines(x, 0, d_train, color='C0', alpha=0.08, lw=0.6, zorder=1)
        ax.vlines(x, 0, d_gen,   color='C1', alpha=0.08, lw=0.6, zorder=1)
        
        # highlight winner lines
        ax.vlines(x[vae_wins], 0, d_gen[vae_wins], color='C1', alpha=0.7, lw=2.0, zorder=2)
        ax.vlines(x[train_wins], 0, d_train[train_wins], color='C0', alpha=0.7, lw=2.0, zorder=2)
    else:
        # standard lines
        ax.vlines(x, 0, d_train, color='C0', alpha=0.25, lw=0.8, zorder=1)
        ax.vlines(x, 0, d_gen,   color='C1', alpha=0.25, lw=0.8, zorder=1)
    
    # markers
    if highlight_markers:
        S_WINNER = 45
        S_LOSER = 12
        s_vae = np.where(vae_wins, S_WINNER, S_LOSER)
        s_train = np.where(train_wins, S_WINNER, S_LOSER)
    else:
        # standard dim
        s_vae = 28
        s_train = 28
    
    lab_train, lab_gen = '$\\Delta$ training (shot noise)', '$\\Delta$ VAE'
    
    ax.scatter(x, d_train, s=s_train, color='C0', edgecolor='white', linewidth=0.4,
               zorder=4, label=lab_train)
    ax.scatter(x, d_gen, s=s_vae, color='C1', edgecolor='white', linewidth=0.4,
               marker='D', zorder=4, label=lab_gen)

    # --- CONFIGURAZIONE ETICHETTE ASSE X ---
    if x_ticks_mode == 'none':
        # Nasconde completamente i ticks e i numeri
        ax.set_xticks([])
    elif x_ticks_mode == 'prob_reference' and sort_by == 'true':
        # Scegliamo 5 indici equispaziati lungo la distribuzione ordinata
        tick_indices = np.linspace(0, n - 1, 5, dtype=int)
        # Creiamo le etichette mostrando il valore di p_exact associato a quell'indice
        tick_labels = [f"$p_{{ex}}$={p_true[idx]:.4f}" for idx in tick_indices]
        
        ax.set_xticks(tick_indices)
        ax.set_xticklabels(tick_labels)
    else:
        # Comportamento standard (mostra gli indici numerici 0, 1, 2...)
        ax.tick_params(axis='x')

    # --- plot configs ---
    ax.set_xlabel('outcomes (sorted by decreasing $p_{exact}$ value)')
    ax.set_xlim(-0.7, n - 0.3)
    ax.set_ylabel('$\\Delta p (p − p_{exact})$' if not abs else '|$\\Delta p$|')
    ax.tick_params(axis='y')
    ax.grid(axis='y', ls=':', alpha=0.4)
    
    # legend
    handles, labels = ax.get_legend_handles_labels()
    by_label = dict(zip(labels, handles))
    ax.legend(by_label.values(), by_label.keys(),  framealpha=0.9, loc='lower right')

    # -- title --
    if title:
        ax.set_title('Deviation from $p_{exact}$: Empirical training frequencies vs VAE', pad=10)

    fig.tight_layout()
    plt.show()

    return fig

def plot_fidelity_vs_samples(results):
    """
    Plot the classical fidelity (Fc) as a function of the number of samples used for training, for different numbers of qubits.
    Args:
        results: dict of the form {n_qubits: {'n_samples': [...], 'Fc': [...]}} containing the number of samples and corresponding fidelities for each qubit count. 
    Returns: figure 
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = plt.cm.viridis(np.linspace(0, 0.85, len(results)))

    for color, (q, r) in zip(colors, sorted(results.items())):
        ns = r["n_samples"]
        ax.plot(ns, r["Fc"], '-o', color=color, label=f'{q} qubit (VAE)')

    ax.set_xscale('log')
    ax.set_xlabel('N_SAMPLES (campioni di training)')
    ax.ylabel('Fidelity classica  $F_c$')
    ax.set_title('Fidelity classica vs N_SAMPLES from 3 to 8 qubit')
    ax.grid(True, which='both', ls=':', alpha=0.5)
    ax.legend()
    fig.tight_layout()
    plt.show()

    return fig

# ----------------------------------------------------------------------------------------------------------------------------
if __name__ == "__main__": 
    def main () :
        print("plots.py has no main")
        return

    main ()
